"""unify_entities_and_uuid_order

Revision ID: d065f66c9b74
Revises: 8ce5dcc55563
Create Date: 2026-08-28 01:49:28.646824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd065f66c9b74'
down_revision: Union[str, Sequence[str], None] = '8ce5dcc55563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_campaigns_daily_menu'), 'collective_pots', type_='foreignkey')
    op.drop_table('hubs')
    op.drop_index(op.f('idx_daily_menus_date'), table_name='daily_menus')
    op.drop_index(op.f('idx_daily_menus_status'), table_name='daily_menus')
    op.drop_table('daily_menus')
    op.alter_column('collective_pots', 'preorder_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('collective_pots', 'live_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('collective_pots', 'sponsor_pack_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('collective_pots', 'discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('20.0'))
    op.alter_column('collective_pots', 'current_revenue',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('collective_pots', 'admin_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_campaigns_active_not_funded'), table_name='collective_pots', postgresql_where="(((status)::text = 'active'::text) AND (daily_menu_id IS NULL))")
    op.drop_index(op.f('idx_campaigns_recipe_date'), table_name='collective_pots')
    op.drop_index(op.f('idx_campaigns_status'), table_name='collective_pots')
    op.drop_index(op.f('idx_campaigns_target_date'), table_name='collective_pots')
    op.create_index(op.f('ix_collective_pots_status'), 'collective_pots', ['status'], unique=False)
    op.create_index(op.f('ix_collective_pots_target_date'), 'collective_pots', ['target_date'], unique=False)
    # op.drop_constraint(op.f('fk_campaigns_daily_menu'), 'collective_pots', type_='foreignkey')
    # op.drop_constraint(op.f('fk_campaigns_pack_launcher'), 'collective_pots', type_='foreignkey')
    # op.drop_constraint(op.f('fk_productions_campaign'), 'productions', type_='foreignkey')
    op.drop_column('collective_pots', 'daily_menu_id')
    op.drop_column('collective_pots', 'pack_launcher_order_id')
    op.add_column('orders', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('portions', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('orders', sa.Column('is_sponsor', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('payment_method_name', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('transaction_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # Drop default before changing type to UUID to avoid cast errors
    # 1. Drop foreign key constraint that depends on the ID being an integer
    op.execute('ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_order_id_fkey')

    # 2. Drop default and alter column to UUID
    op.execute('ALTER TABLE orders ALTER COLUMN id DROP DEFAULT')
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using='gen_random_uuid()',
               existing_nullable=False)

    # 3. Alter the dependent column in transactions
    op.alter_column('transactions', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using='NULL', # Existing data link will be broken if we use gen_random_uuid()
               existing_nullable=True)

    # 4. Re-add the foreign key constraint
    op.create_foreign_key('transactions_order_id_fkey', 'transactions', 'orders', ['order_id'], ['id'])
    op.alter_column('user_events', 'event_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_events_created'), table_name='user_events')
    op.drop_index(op.f('idx_events_phone'), table_name='user_events')
    op.drop_index(op.f('idx_events_type'), table_name='user_events')
    op.create_index(op.f('ix_user_events_event_type'), 'user_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
    op.create_index(op.f('ix_user_events_phone'), 'user_events', ['phone'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('users', 'can_receive_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_receive_tasks', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_user_events_phone'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_type'), table_name='user_events')
    op.create_index(op.f('idx_events_type'), 'user_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_events_phone'), 'user_events', ['phone'], unique=False)
    op.create_index(op.f('idx_events_created'), 'user_events', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('user_events', 'event_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('transactions', 'order_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_suggestions_is_active'), table_name='suggestions')
    op.create_index(op.f('idx_suggestions_product_id'), 'suggestions', ['product_id'], unique=False)
    op.create_index(op.f('idx_suggestions_is_active'), 'suggestions', ['is_active'], unique=False)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'price_family',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'price_duo',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'price_solo',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'video_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('productions', sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'productions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_productions_campaign'), 'productions', 'collective_pots', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'productions', type_='unique')
    op.drop_index(op.f('ix_productions_dispatch_status'), table_name='productions')
    op.create_unique_constraint(op.f('productions_campaign_id_key'), 'productions', ['campaign_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_productions_dispatch_status'), 'productions', ['dispatch_status'], unique=False)
    op.create_index(op.f('idx_productions_campaign_id'), 'productions', ['campaign_id'], unique=False)
    op.drop_column('productions', 'collective_pot_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_collective_pot_id'), table_name='orders')
    op.create_unique_constraint(op.f('orders_idempotency_key_key'), 'orders', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('idx_orders_idempotency'), 'orders', ['idempotency_key'], unique=False)
    op.create_index(op.f('idx_orders_campaign_id'), 'orders', ['collective_pot_id'], unique=False)
    op.alter_column('orders', 'zone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'transaction_id')
    op.drop_column('orders', 'payment_method_name')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'is_sponsor')
    op.drop_column('orders', 'portions')
    op.drop_column('orders', 'user_id')
    op.add_column('collective_pots', sa.Column('pack_launcher_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('collective_pots', sa.Column('daily_menu_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_campaigns_daily_menu'), 'collective_pots', 'daily_menus', ['daily_menu_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_campaigns_pack_launcher'), 'collective_pots', 'orders', ['pack_launcher_order_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_collective_pots_target_date'), table_name='collective_pots')
    op.drop_index(op.f('ix_collective_pots_status'), table_name='collective_pots')
    op.create_index(op.f('idx_campaigns_target_date'), 'collective_pots', ['target_date'], unique=False)
    op.create_index(op.f('idx_campaigns_status'), 'collective_pots', ['status'], unique=False)
    op.create_index(op.f('idx_campaigns_recipe_date'), 'collective_pots', ['product_id', 'target_date'], unique=False)
    op.create_index(op.f('idx_campaigns_active_not_funded'), 'collective_pots', ['status', 'daily_menu_id'], unique=False, postgresql_where="(((status)::text = 'active'::text) AND (daily_menu_id IS NULL))")
    op.alter_column('collective_pots', 'admin_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('collective_pots', 'current_revenue',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('collective_pots', 'discount_percentage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('20.0'))
    op.alter_column('collective_pots', 'sponsor_pack_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('collective_pots', 'live_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('collective_pots', 'preorder_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.create_table('daily_menus',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('occurrence_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('cutoff_time', postgresql.TIME(), server_default=sa.text("'22:00:00'::time without time zone"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'SCHEDULED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('minimum_production', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('max_production', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reserved_portions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('pack_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('individual_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('launch_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('launched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bonus_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'PREORDER_OPEN'::character varying, 'PRODUCTION_CONFIRMED'::character varying, 'PRODUCTION_CLOSED'::character varying, 'DELIVERED'::character varying]::text[])", name=op.f('chk_valid_status')),
    sa.CheckConstraint('pack_price > 0::numeric AND individual_price > 0::numeric', name=op.f('chk_prices_positive')),
    sa.CheckConstraint('reserved_portions >= 0', name=op.f('chk_reserved_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_daily_menus_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_menus_pkey')),
    sa.UniqueConstraint('product_id', 'occurrence_date', name=op.f('uq_product_per_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_daily_menus_status'), 'daily_menus', ['status'], unique=False)
    op.create_index(op.f('idx_daily_menus_date'), 'daily_menus', ['occurrence_date'], unique=False)
    op.create_table('hubs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('active_productions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('pending_orders', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('revenue_today', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hubs_pkey'))
    )
    # ### end Alembic commands ###
