"""final_entity_sync

Revision ID: d2999a3bf96a
Revises: d065f66c9b74
Create Date: 2026-08-28 01:53:27.809604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2999a3bf96a'
down_revision: Union[str, Sequence[str], None] = 'd065f66c9b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    # Ensure paymentmethod enum exists
    result = bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'paymentmethod'"))
    if not result.first():
        payment_method_enum = postgresql.ENUM('ORANGE_MONEY', 'MTN_MOBILE_MONEY', 'CASH', name='paymentmethod')
        payment_method_enum.create(bind)

    if 'analytics' not in tables:
        op.create_table('analytics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=True),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'delivery_settings' not in tables:
        op.create_table('delivery_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('zones', sa.JSON(), nullable=True),
        sa.Column('base_price', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_delivery_settings_id'), 'delivery_settings', ['id'], unique=False)

    if 'password_reset_tokens' not in tables:
        op.create_table('password_reset_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
        op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)

    if 'products' not in tables:
        op.create_table('products',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('video_url', sa.String(length=500), nullable=True),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('price_solo', sa.Float(), nullable=True),
        sa.Column('price_duo', sa.Float(), nullable=True),
        sa.Column('price_family', sa.Float(), nullable=True),
        sa.Column('family_size', sa.Integer(), nullable=True),
        sa.Column('complements', sa.String(length=255), nullable=True),
        sa.Column('is_hero', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)

    if 'reels' not in tables:
        op.create_table('reels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('product_name', sa.String(length=255), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('price_solo', sa.Float(), nullable=True),
        sa.Column('price_duo', sa.Float(), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('is_available', sa.Boolean(), nullable=True),
        sa.Column('price_family', sa.Float(), nullable=True),
        sa.Column('family_size', sa.Integer(), nullable=True),
        sa.Column('complements', sa.String(length=255), nullable=True),
        sa.Column('likes_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('video_url', sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_reels_id'), 'reels', ['id'], unique=False)

    if 'user_events' not in tables:
        op.create_table('user_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('product_name', sa.String(length=255), nullable=True),
        sa.Column('video_id', sa.Integer(), nullable=True),
        sa.Column('cart_value', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('affiliate_code', sa.String(length=20), nullable=True),
        sa.Column('event_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('session_id', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_events_event_type'), 'user_events', ['event_type'], unique=False)
        op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
        op.create_index(op.f('ix_user_events_phone'), 'user_events', ['phone'], unique=False)

    if 'users' not in tables:
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('customer_name', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('permissions', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('can_view_stats', sa.Boolean(), nullable=True),
        sa.Column('can_edit_orders', sa.Boolean(), nullable=True),
        sa.Column('is_affiliate', sa.Boolean(), nullable=True),
        sa.Column('affiliate_code', sa.String(), nullable=True),
        sa.Column('pending_commissions', sa.Float(), nullable=True),
        sa.Column('total_earned', sa.Float(), nullable=True),
        sa.Column('last_payout_date', sa.DateTime(), nullable=True),
        sa.Column('expo_push_token', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('has_requested_affiliate', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_affiliate_code'), 'users', ['affiliate_code'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
        op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    if 'suggestions' not in tables:
        op.create_table('suggestions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('suggested_date', sa.DateTime(), nullable=True),
        sa.Column('suggested_by_user_id', sa.String(length=255), nullable=True),
        sa.Column('interest_count', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_suggestions_is_active'), 'suggestions', ['is_active'], unique=False)

    if 'collective_pots' not in tables:
        op.create_table('collective_pots',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('suggestion_id', sa.UUID(), nullable=True),
        sa.Column('target_date', sa.Date(), nullable=False),
        sa.Column('minimum_orders', sa.Integer(), nullable=False),
        sa.Column('max_orders', sa.Integer(), nullable=True),
        sa.Column('preorder_price', sa.Float(), nullable=False),
        sa.Column('live_price', sa.Float(), nullable=False),
        sa.Column('sponsor_pack_price', sa.Float(), nullable=False),
        sa.Column('discount_percentage', sa.Float(), nullable=False),
        sa.Column('current_orders', sa.Integer(), nullable=False),
        sa.Column('current_revenue', sa.Float(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('bonus_description', sa.String(length=255), nullable=True),
        sa.Column('admin_notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('funded_at', sa.DateTime(), nullable=True),
        sa.CheckConstraint('current_orders >= 0', name='chk_cp_current_orders_non_negative'),
        sa.CheckConstraint('discount_percentage >= 0 AND discount_percentage <= 50', name='chk_cp_discount_range'),
        sa.CheckConstraint('minimum_orders > 0', name='chk_cp_min_orders_positive'),
        sa.CheckConstraint('preorder_price > 0 AND live_price > 0 AND sponsor_pack_price > 0', name='chk_cp_prices_positive'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_collective_pots_status'), 'collective_pots', ['status'], unique=False)
        op.create_index(op.f('ix_collective_pots_target_date'), 'collective_pots', ['target_date'], unique=False)

    if 'orders' not in tables:
        op.create_table('orders',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('collective_pot_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.String(length=255), nullable=True),
        sa.Column('customer_name', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('product_name', sa.String(length=255), nullable=True),
        sa.Column('portions', sa.Integer(), nullable=False),
        sa.Column('portion_size', sa.String(length=100), nullable=True),
        sa.Column('complement', sa.String(length=255), nullable=True),
        sa.Column('option_selected', sa.String(length=255), nullable=True),
        sa.Column('zone', sa.String(length=100), nullable=True),
        sa.Column('delivery_date', sa.String(length=100), nullable=True),
        sa.Column('delivery_time', sa.String(length=100), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=False),
        sa.Column('deposit_amount', sa.Float(), nullable=False),
        sa.Column('is_sponsor', sa.Boolean(), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=True),
        sa.Column('payment_status', sa.String(length=32), nullable=True),
        sa.Column('payment_method_name', sa.String(length=50), nullable=True),
        sa.Column('transaction_id', sa.String(length=255), nullable=True),
        sa.Column('idempotency_key', sa.String(length=255), nullable=True),
        sa.Column('affiliate_code', sa.String(length=50), nullable=True),
        sa.Column('affiliate_payout_phone', sa.String(length=20), nullable=True),
        sa.Column('commission_paid', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['collective_pot_id'], ['collective_pots.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_orders_affiliate_code'), 'orders', ['affiliate_code'], unique=False)
        op.create_index(op.f('ix_orders_collective_pot_id'), 'orders', ['collective_pot_id'], unique=False)
        op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
        op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
        op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
        op.create_index(op.f('ix_orders_phone'), 'orders', ['phone'], unique=False)
        op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
        op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)

    if 'productions' not in tables:
        op.create_table('productions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('collective_pot_id', sa.UUID(), nullable=False),
        sa.Column('chef_name', sa.String(length=255), nullable=True),
        sa.Column('hub_location', sa.String(length=100), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('cooking_temperature', sa.Integer(), nullable=True),
        sa.Column('batch_id', sa.String(length=64), nullable=True),
        sa.Column('packaging_type', sa.String(length=50), nullable=True),
        sa.Column('dispatch_status', sa.String(length=32), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['collective_pot_id'], ['collective_pots.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('collective_pot_id')
        )
        op.create_index(op.f('ix_productions_dispatch_status'), 'productions', ['dispatch_status'], unique=False)

    if 'transactions' not in tables:
        op.create_table('transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.UUID(), nullable=True),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('transaction_type', sa.String(length=50), nullable=False),
        sa.Column('payment_reference', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('payment_method', postgresql.ENUM('ORANGE_MONEY', 'MTN_MOBILE_MONEY', 'CASH', name='paymentmethod', create_type=False), nullable=True),
        sa.Column('operator_reference', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('operator_reference'),
        sa.UniqueConstraint('payment_reference')
        )
        op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_productions_dispatch_status'), table_name='productions')
    op.drop_table('productions')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_collective_pot_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_affiliate_code'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_collective_pots_target_date'), table_name='collective_pots')
    op.drop_index(op.f('ix_collective_pots_status'), table_name='collective_pots')
    op.drop_table('collective_pots')
    op.drop_index(op.f('ix_suggestions_is_active'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_affiliate_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_events_phone'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_type'), table_name='user_events')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_reels_id'), table_name='reels')
    op.drop_table('reels')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_delivery_settings_id'), table_name='delivery_settings')
    op.drop_table('delivery_settings')
    op.drop_table('analytics')
    # ### end Alembic commands ###
